---
# tasks file for configure_nginx

- name: create nginx repo definition
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
    tags: [nginx]

- name: install nginx
  apt:
    name: nginx
    update_cache: true
    state: present
  tags: [nginx]

- name: copy main nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: [nginx]

- name: copy site's nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/notls.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: [nginx]

- name: copy index.html
  copy:
    src: site/
    dest: /usr/share/nginx/html/
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: [html]

- name: copy index.html template
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: [html]

- name: ensure nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: true
  tags: [healthcheck]

- name: insert firewalld rule for nginx
  firewalld:
    port: "{{ nginx_port_with_tls }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
  tags: [nginx]

